//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFinal.BancoPds
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_PEDIDO
    {
        public long id_produto { get; set; }
        public long id_pedido { get; set; }
        public string quantidade { get; set; }
        public string valor_parcial { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
