//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFinal.BancoPds
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.PRODUTO_PEDIDO = new HashSet<PRODUTO_PEDIDO>();
        }
    
        public long id_produto { get; set; }
        public string descricao { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<long> id_tipo_produto { get; set; }
        public string estoque { get; set; }
        public Nullable<long> id_fabricante { get; set; }
    
        public virtual FABRICANTE FABRICANTE { get; set; }
        public virtual TIPO_PRODUTO TIPO_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_PEDIDO> PRODUTO_PEDIDO { get; set; }
    }
}
